{
  "comments": [
    {
      "key": {
        "uuid": "70895b9c_dd8a6540",
        "filename": "services/net/java/android/net/IpMemoryStore.java",
        "patchSetId": 5
      },
      "lineNbr": 56,
      "author": {
        "id": 1015428
      },
      "writtenOn": "2019-04-01T07:03:53Z",
      "side": 1,
      "message": "I don\u0027t think there is a point in saying this. It\u0027s an implementation detail, and it\u0027s a grand total of 1 lines of code in this file, it should be pretty obvious.",
      "range": {
        "startLine": 55,
        "startChar": 26,
        "endLine": 56,
        "endChar": 17
      },
      "revId": "5611ba92c5e181855d8d156a65223d389375ee17",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "63a73eda_a96223b2",
        "filename": "services/net/java/android/net/IpMemoryStore.java",
        "patchSetId": 5
      },
      "lineNbr": 58,
      "author": {
        "id": 1015428
      },
      "writtenOn": "2019-04-01T07:03:53Z",
      "side": 1,
      "message": "How did you make sure this is true ?",
      "range": {
        "startLine": 57,
        "startChar": 26,
        "endLine": 58,
        "endChar": 16
      },
      "revId": "5611ba92c5e181855d8d156a65223d389375ee17",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "3da441b7_bfdc817f",
        "filename": "services/net/java/android/net/IpMemoryStore.java",
        "patchSetId": 5
      },
      "lineNbr": 63,
      "author": {
        "id": 1015428
      },
      "writtenOn": "2019-04-01T07:03:53Z",
      "side": 1,
      "message": "Wait, I was confused. An exception is definitely possible here (all a client has to do is to pass a consumer that throws ; we control the code that passes the consumers so hopefully it will never happen, but better safe than sorry). I was referring to the fact that it\u0027s impossible that the memory store fetched in line 46 was null, but here we need to make sure we don\u0027t throw. Therefore, I think we need to surround l.65 with a try {} catch (Exception e) { Log.wtf(); } to be sure we always return the store.",
      "range": {
        "startLine": 63,
        "startChar": 15,
        "endLine": 63,
        "endChar": 65
      },
      "revId": "5611ba92c5e181855d8d156a65223d389375ee17",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}