{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "359feb95_6886dc19",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1432579
      },
      "writtenOn": "2021-01-25T23:18:21Z",
      "side": 1,
      "message": "I think this issue is already fixed in an internal branch. +Samiul to keep me honest",
      "revId": "580d241a6b22e004b060eeba41ba9760b8fda6da",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}