{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "ca53885f_b92065d6",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1352498
      },
      "writtenOn": "2021-03-16T01:13:35Z",
      "side": 1,
      "message": "looks like one testcase (which might have dependency to this one) is broken.\n\n```\njava.lang.AssertionError\njava.lang.AssertionError\n\tat org.junit.Assert.fail(Assert.java:87)\n\tat org.junit.Assert.assertTrue(Assert.java:42)\n\tat org.junit.Assert.assertFalse(Assert.java:65)\n\tat org.junit.Assert.assertFalse(Assert.java:75)\n\tat com.android.internal.telephony.dataconnection.DataConnectionTest.testOverrideUnmetered(DataConnectionTest.java:695)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)\n\tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n\tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:61)\n\tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n\tat org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:148)\n\tat org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:142)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.lang.Thread.run(Thread.java:920)\n```",
      "revId": "6986e790c0f15e4432c3d68a95f3012ccf117ea1",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}