{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "ac075f3b_7594cccc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1064003
      },
      "writtenOn": "2023-10-25T23:27:02Z",
      "side": 1,
      "message": "Looking into boot failure that wasn\u0027t present on internal git_main",
      "revId": "c0a34a3ced664dc7ef34b606eb821fc9331780b6",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}